# Workflow for deploying a Next.js app to GitHub Pages
name: Deploy Next.js app to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Use the Node.js version your Next.js app requires

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        env:
          NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}
        run: npm run build && npm run export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "out" # Adjust to the export directory of your Next.js app

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
